apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/publisher/
patches:
- path: ./dev-publisher-patch-deploy.yaml
- path: ./dev-publisher-patch-service.yaml
images:
- name: service-image
  newName: publisher/service/publisher-api
  newTag: 0.0.1
